routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('admin.dashboard');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::prefix('dashboard')->name('dashboards.')->group(function () {
        Route::get('', 'AdminController@index')->name('index');
    });
    Route::prefix('items')->name('items.')->group(function () {
        Route::get('', 'ItemController@item')->name('items');
        Route::get('item_list', 'ItemController@item_list')->name('item_list');
        Route::post('item_request', 'ItemController@item_request')->name('item_request');
    });
});

app/Admin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Admin extends Model
{
    //
}

app/CostAccountType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CostAccountType extends Model
{
    //
}

app/ItemUnit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ItemUnit extends Model
{
    //
}

app/SaleAccountType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SaleAccountType extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class item extends Model
{
    //
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index()
    {
        return view('admin.dashboard');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CostAccountTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CostAccountTypeController extends Controller
{
    //
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\CostAccountType;
use App\item;
use App\ItemUnit;
use App\SaleAccountType;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class ItemController extends Controller
{
    public function item()
    {
        $items = Item::all();
        $item_units = ItemUnit::all();
        $sale_types = SaleAccountType::all();
        $cost_types = CostAccountType::all();
        return view('admin.inventory.items')->with(['items' => $items,'item_units'=>$item_units,'sale_types'=>$sale_types,'cost_types'=>$cost_types]);
    }
    public function item_list(Request $request)
    {
        $items = item::select('id','item_type','name','sku_id','item_unit','cost_price','sale_price','created_at')->get();

        if ($request->get('search_date_from') && $request->get('search_date_to')) {

            $from = $request->get('search_date_from');
            $to = $request->get('search_date_to');
            $stop_date = date('Y-m-d H:i:s', strtotime($to . ' +1 day'));
            $items->whereBetween('items.created_at', [$from, $stop_date]);
        }
        $datatables = Datatables::of($items)

            ->editColumn('item_type', function ($items) {
                if ($items->item_type == 0) {
                    return 'Goods';
                } else {
                    return 'Service';
                }
            })
            ->addColumn('action', function ($reminder_request) {
                $reminder_button = '<a href="javascript:void(0);" class="dropdown-item reminderMarkStatus" data-action="reminder"><i class="ft-plus-circle primary"></i> Edit </a>';
                $reminder_button1 = '<a href="javascript:void(0);" class="dropdown-item reminderMarkStatus" data-action="reminder"><i class="ft-plus-circle primary"></i> Delete</a>';


                    $dropdown = "
                        <div class='btn-group'>
                           <button type='button' class='btn btn-sm btn-success dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>Actions</button>
                            <div class='dropdown-menu dropdown-menu-sm'>";
                    $dropdown .= $reminder_button;
                    $dropdown .= $reminder_button1;
                    $dropdown .= "
                            </div>
                        </div>
                    ";

                    return $dropdown;
            });

        return $datatables->make(true);
    }
    public function item_request(Request $request)
    {
        $item = new Item();
        $item->item_type = $request->item_type;
        $item->name = $request->name;
        $item->sku_id = $request->sku_id;
        $item->item_unit = $request->item_unit;
        $item->sale_price = $request->sale_price;
        $item->sale_account_id = $request->sale_type;
        $item->sale_description = $request->sale_description;
        $item->cost_price = $request->cost_price;
        $item->cost_account_id = $request->cost_type;
        $item->cost_description = $request->cost_description;
        $item->sale_tax = $request->sale_tax;
        $item->save();
        return redirect()->back()->with('success','Item Added');
    }
}

app/Http/Controllers/ItemUnitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ItemUnitController extends Controller
{
    //
}

app/Http/Controllers/SaleAccountTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SaleAccountTypeController extends Controller
{
    //
}

resources/views/admin/inc/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif
@if(session('info'))
    <div class="alert alert-warning">
        {{session('info')}}
    </div>
@endif

resources/views/admin/layout/footer.blade.php
<footer class="footer footer-static footer-light navbar-border navbar-shadow">
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
        <span class="float-md-left d-block d-md-inline-block font-weight-bold"><i class="ft-phone-call align-middle mr-1"></i><span class="align-middle">021-111-118-729</span></span>
        <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Copyright &copy; {{ now()->year }} By <a class="text-bold-800 grey darken-2" href="#">Trax</a>, All Rights Reserved.</span>
    </p>
</footer>
<!-- BEGIN VENDOR JS-->
<script src="{{asset('app-assets/vendors/js/vendors.min.js')}}" type="text/javascript"></script>
<!-- BEGIN VENDOR JS-->
<script src="{{asset('js/main-2.2.js')}}" type="text/javascript"></script>
{{--This needs to be moved--}}
<script src="{{asset('app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js')}}" type="text/javascript"></script>
{{--This needs to be moved--}}
<!-- BEGIN PAGE VENDOR JS-->
{{--<script src="{{asset('app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}" type="text/javascript"></script>--}}
{{--<script src="{{asset('app-assets/vendors/js/forms/icheck/icheck.min.js')}}" type="text/javascript"></script>--}}
<!-- END PAGE VENDOR JS-->
<!-- BEGIN MODERN JS-->
<script src="{{asset('app-assets/js/core/app-menu.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/js/core/app.js')}}" type="text/javascript"></script>
<!-- END MODERN JS-->

<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('app-assets/vendors/js/extensions/sweetalert.min.js')}}" type="text/javascript"></script>
{{--<script src="{{asset('app-assets/js/scripts/forms/form-login-register.js')}}" type="text/javascript"></script>--}}
{{--Datatables javascript--}}
{{--This needs to be moved--}}
<script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-switch.min.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/js/scripts/forms/switch.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/js/scripts/forms/input-groups.js')}}" type="text/javascript"></script>
{{--<script src="{{asset('app-assets/vendors/js/pickers/pickadate/picker.date.js')}}" type="text/javascript"></script>--}}
<script src="{{asset('app-assets/vendors/js/pickers/daterange/daterangepicker.js')}}" type="text/javascript"></script>
{{--This needs to be moved--}}
{{--<script src="{{asset('app-assets/js/scripts/pickers/dateTime/pick-a-datetime.js')}}" type="text/javascript"></script>--}}
<script src="{{asset('app-assets/vendors/js/tables/datatable/datatables.min.js')}}" type="text/javascript"></script>
<script src="{{asset('app-assets/js/scripts/tables/datatables/datatable-basic.js')}}" type="text/javascript"></script>

@if (isset($ticker))
    <script src="{{asset('app-assets/vendors/js/marquee3000/marquee3k.js')}}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            Marquee3k.init();
        });
    </script>
@endif

<script src="{{asset('js/app.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->
<script type="text/javascript">
    $(document).ready(function () {
        $('body #app_content').on('click', function () {
            if($('#sidebar_menu').hasClass('is-active')){
                $.app.menu.hide();
            }
        });
        {{--        @if(Session::has('first_login') && session('first_login') != 1)--}}
        {{--            $('#FirstLoginPasswordChangeModal').modal('show');--}}

        {{--            $('#first_peye').on('mousedown',function(){$('input[name="current_password"]').attr('type','text')}).on('mouseup',function(){$('input[name="current_password"]').attr('type','password')});--}}
        {{--            $('#first_npeye').on('mousedown',function(){$('input[name="password"]').attr('type','text')}).on('mouseup',function(){$('input[name="password"]').attr('type','password')});--}}
        {{--            $('#first_cpeye').on('mousedown',function(){$('input[name="confirm_password"]').attr('type','text')}).on('mouseup',function(){$('input[name="confirm_password"]').attr('type','password')});--}}

        {{--        $( "#password-form" ).validate({--}}
        {{--            errorClass:"danger",--}}
        {{--            normalizer: function(value) {--}}
        {{--                return $.trim(value);--}}
        {{--            },--}}
        {{--            errorPlacement: function(error, element) {--}}
        {{--                error.addClass('w-100').appendTo(element.parent('.form-group'));--}}
        {{--            },--}}
        {{--            submitHandler: function(form) {--}}
        {{--                var current_password = $('#current_password').val();--}}
        {{--                var new_password = $('#new_password').val();--}}
        {{--                var confirm_password = $('#confirm_password').val();--}}
        {{--                if (current_password !== new_password) {--}}
        {{--                    if(new_password === confirm_password){--}}
        {{--                        swal({--}}
        {{--                            title: 'Please Wait!',--}}
        {{--                            text: 'Password is being updated!',--}}
        {{--                            icon: 'info',--}}
        {{--                            buttons: false,--}}
        {{--                            closeOnClickOutside: false,--}}
        {{--                            closeOnEsc: false--}}
        {{--                        });--}}
        {{--                        form.submit();--}}
        {{--                    }--}}
        {{--                    else{--}}
        {{--                        var error = "The password and confirmation password do not match";--}}
        {{--                        toastr.error(error, 'Error!', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});--}}
        {{--                    }--}}
        {{--                }--}}
        {{--                else{--}}
        {{--                    var error = "The current and new password cannot be same";--}}
        {{--                    toastr.error(error, 'Error!', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});--}}
        {{--                }--}}
        {{--            }--}}
        {{--        });--}}
        {{--        @endif--}}

        function getLocation() {
            swal({
                text: 'Please Wait!',
                icon: 'info',
                buttons: false,
                closeOnClickOutside: false,
                closeOnEsc: false
            });

            setTimeout(function() {
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(locationSuccess, locationFail);
                }
                else {
                    locationFail();
                }
            }, 250);
        }

        function check_profile() {
            $.ajax({
                {{--url: '{{ route('admin.update_one_time_profile.check') }}',--}}
                url: '',
                method: 'GET'
            }).done(function (data) {
                if (data.status == 1) {
                    toastr.error(data.error, 'Error!', {
                        positionClass: 'toast-top-center',
                        containerId: 'toast-top-center'
                    });
                } else if(data.status == 0) {
                    $('#EditOneTimeProfileModal').modal('show');
                }
            });
        }

        function locationSuccess(position) {
            $.ajax({
                {{--url: '{{ route('admin.save_coordinates') }}',--}}
                url: '',
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                data: {
                    'longitude': position.coords.longitude,
                    'latitude': position.coords.latitude
                }
            });

            $('#LocationDeniedModal').modal('hide');
            swal.close();
{{--            @if(!Illuminate\Support\Facades\Route::is('admin.update_one_time_profile.index'))--}}
{{--            check_profile();--}}
{{--            @endif--}}
        }

        function locationFail() {
            swal.close();
            $('#LocationDeniedModal').modal('show');
        }

        $('#EditOneTimeProfileModal form button').bind('click', function() {
            $('#EditOneTimeProfileModal').modal('hide');
            {{--window.location.href = "{{route("admin.update_one_time_profile.index")}}";--}}
                window.location.href = "";
        });

        $('#LocationDeniedModal form button').bind('click', function() {
            getLocation();
        });

        getLocation();
    });
</script>
@yield('js')

resources/views/admin/layout/header.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="Trax, Sonic">
<meta name="keywords" content="Trax">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="author" content="Trax IT">
<title>@yield('title') - Sonic | Trax</title>
<link rel="apple-touch-icon" sizes="152x152" href="{{ asset('img/apple-touch-icon_new.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('img/favicon_new-32x32.png') }} ">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('img/favicon_new-16x16.png') }}">
<link rel="shortcut icon" type="image/x-icon" href="{{  asset('img/favicon_new.ico') }}">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700"
      rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/fonts/line-awesome/css/line-awesome.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/vendors.css')}}">
{{--This needs to be moved--}}
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/pickers/daterange/daterangepicker.css')}}">

<link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/forms/toggle/bootstrap-switch.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/forms/toggle/switchery.min.css')}}">
{{--This needs to be moved--}}
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/tables/datatable/datatables.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/app.css')}}">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{{--Alerts--}}
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/modal/sweetalert.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/core/menu/menu-types/vertical-overlay-menu.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/core/colors/palette-gradient.css')}}">
{{--This needs to be moved--}}
<link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/plugins/forms/switch.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/style.css')}}">

@yield('css')

<link rel="stylesheet" type="text/css" href="{{asset('css/custom.css')}}">

resources/views/admin/layout/master.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    @include('admin.layout.header')
</head>
<body class="vertical-layout vertical-overlay-menu 2-columns   menu-expanded fixed-navbar"
      data-open="click" data-menu="vertical-overlay-menu" data-col="2-columns">
<!-- fixed-top-->
@include('admin.layout.navbar')

@include('admin.layout.sidebar')
<div class="app-content content" id="app_content">
    <div class="content-wrapper">
        @if (isset($ticker))
            <div class="marquee3k" data-speed="0.25" data-pausable="bool">
                <span>{{ $ticker }}</span>
            </div>
        @endif

        <div class="content-body">
            @yield('content')
        </div>
    </div>
</div>
@include('admin.components.modals')
@include('admin.layout.footer')
{{--@include('admin.layout.sonic_search')--}}
<audio id="audio_success" autostart="false">
    <source src="{{asset('file/success_sound.mp3')}}" type="audio/ogg">
    <source src="{{asset('file/success_sound.mp3')}}" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>
<audio id="audio_error" autostart="false">
    <source src="{{asset('file/error.mp3')}}" type="audio/ogg">
    <source src="{{asset('file/error.mp3')}}" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>
</body>
</html>

resources/views/admin/layout/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-bordered menu-shadow"
     data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class=" nav-item"><a href="{{route('admin.dashboards.index')}}"><i class="la la-area-chart"></i>
                    <span class="menu-title" data-i18n="nav.dash.main">Dashboard</span></a>
            </li>
            <li class=" nav-item"><a href="#"><span class="menu-title" data-i18n="nav.vertical_nav.main"><i
                            class="la la-cart-plus"></i>Items</span></a>
                <ul class="menu-content">
                    <li><a class="menu-item" href="{{route('admin.items.items')}}">Items</a></li>
                    <li><a class="menu-item" href="">Price Lists</a></li>
                    <li><a class="menu-item" href="">Inventory Adjustments</a></li>
                    <li><a class="menu-item" href="">Notes</a></li>

                </ul>
            </li>

            <li><a class="menu-item" href=""><i class="la la-university"></i>Banking</a></li>

            <li class=" nav-item"><a href="#"><span class="menu-title" data-i18n="nav.vertical_nav.main"><i
                            class="la la-shopping-cart "></i>Sales</span></a>
                <ul class="menu-content">
                    <li><a class="menu-item" href="">Customers</a></li>
                    <li><a class="menu-item" href="">Estimates</a></li>
                    <li><a class="menu-item" href="">Retainer Invoice</a></li>
                    <li><a class="menu-item" href="">Sales Order</a></li>
                    <li><a class="menu-item" href="">Delivery Challans</a></li>
                    <li><a class="menu-item" href="">Invoices</a></li>
                    <li><a class="menu-item" href="">Payment Received</a></li>
                    <li><a class="menu-item" href="">Recurring Invoices</a></li>
                    <li><a class="menu-item" href="">Credit Notes</a></li>
                </ul>
            </li>
            <li class="divider"></li>

            <li class=" nav-item"><a href="#"><span class="menu-title" data-i18n="nav.vertical_nav.main"><i
                            class="las la-shopping-basket"></i>Purchases</span></a>
                <ul class="menu-content">
                    <li><a class="menu-item" href="">Vendor</a></li>
                    <li><a class="menu-item" href="">Expenses</a></li>
                    <li><a class="menu-item" href="">Recurring Expenses</a></li>
                    <li><a class="menu-item" href="">Purchase Orders</a></li>
                    <li><a class="menu-item" href="">Bills</a></li>
                    <li><a class="menu-item" href="">Payment Made</a></li>
                    <li><a class="menu-item" href="">Recurring Bills</a></li>
                    <li><a class="menu-item" href="">Vendor Credits</a></li>
                    <li><a class="menu-item" href="">Credit Notes</a></li>
                </ul>
            </li>
            <li class=" nav-item"><a href="#"><span class="menu-title" data-i18n="nav.vertical_nav.main"><i
                            class="las la-file-invoice"></i>Accountant</span></a>
                <ul class="menu-content">
                    <li><a class="menu-item" href="">Manual Journals</a></li>
                    <li><a class="menu-item" href="">Bulk Update</a></li>
                    <li><a class="menu-item" href="">Currency Adjustments</a></li>
                    <li><a class="menu-item" href="">Chart of Accounts</a></li>
                    <li><a class="menu-item" href="">Budgets</a></li>
                    <li><a class="menu-item" href="">Transaction Locking</a></li>
                </ul>
            </li>
            <li><a class="menu-item" href=""><i class="las la-file-image"></i>Reports</a></li>

        </ul>
    </div>
</div>